### ISSUE TITLE
[macOS] NSUserNotificationCenter is deprecated

### ISSUE THREAD

**Issue by cbenhagen** [leanflutter/local_notifier#13]
While checking the docs on another issue, I stumbled on the deprecation warning. Apple recomends to use the [User Notifications](https://developer.apple.com/documentation/usernotifications) framework instead.

**Comment by cbenhagen** [comment]
True, Flutter supports 10.11+ so maybe there could be a different implementation using `NSUserNotificationCenter ` for users below 10.14?

**Comment by pft-TommyChang** [comment]
```
/local_notifier/local_notifier.framework/Headers/local_notifier-Swift.h:318:33: warning: 'NSUserNotificationCenter' is deprecated: first deprecated in macOS 11.0 - All NSUserNotifications API should be replaced with UserNotifications.frameworks API
```
We face same warning, consider use the [User Notifications](https://developer.apple.com/documentation/usernotifications) framework instead.
