### ISSUE TITLE
[Windows] No logo

### ISSUE THREAD

**Issue by ollydixon** [leanflutter/local_notifier#14]
The logo area is blank on Windows.

Side note
Have you considered making a PR with flutter_local_notifications for an all in one notification package?

**Comment by ollydixon** [comment]
For anyone else, if you install with msix you get a logo.

**Comment by lijy91** [comment]
He seems to be related to SHORTCUT_POLICY https://github.com/leanflutter/local_notifier/commit/f21669607bf610ce67efbd3db673d7b5320fe7e2

**Comment by lijy91** [comment]
Please update to v0.1.5

**Comment by ollydixon** [comment]
I noticed that you removed the setAppName, guess it's not needed?

**Comment by lijy91** [comment]
> I noticed that you removed the setAppName, guess it's not needed?

Now use the `setup` method to set it up

**Comment by ollydixon** [comment]
@lijy91 what does this do, what is the name supposed to be? com.company.app or "exact-app-name" ?

Or is it just what is displayed when the notif appears?

**Comment by lijy91** [comment]
exact-app-name, for windows the generated shortcut name is appName.

**Comment by ollydixon** [comment]
@lijy91 I'm not sure what that means, how do we know what "appName" is?

**Comment by ollydixon** [comment]
@lijy91 the display name is different to the exact-app-name though.

For example
We have an app with the display name "PowGo" but the exact app name is "powgo" :-D

So it should be PowGo? What is it used for? Linking to the app? If that's the case wouldn't it be the package name?

**Comment by lijy91** [comment]
On windows, you need to create a shortcut in the start menu. The name of the shortcut is appName.link , regardless of the package name.

This comment explains why the shortcut is needed.
https://github.com/leanflutter/local_notifier/issues/9#issuecomment-1145850323

**Comment by ollydixon** [comment]
@lijy91 this needs to be in the docs or at least in the code docs.

Users are not going to manually create shortcuts in the start menu though? Unless you do it for them via [msix](https://github.com/YehudaKremer/msix)

I still don't understand what are supposed to use here. ```appName.link``` what is this? 🫤
