### ISSUE TITLE
Toast Not Showing and only print xml code on terminal

### ISSUE THREAD

**Issue by ekokurniadi** [leanflutter/local_notifier#18]
xml: <toast template="ToastGeneric" duration="long" scenario="Default"><visual><binding template="ToastText02"><text id="1">example</text><text id="2">hello flutter!</text></binding></visual><actions><action content="Yes" arguments="0"/><action content="No" arguments="1"/></actions></toast>
flutter: onShow _exampleNotification
xml: <toast scenario="Default"><visual><binding template="ToastText02"><text id="1">example - 0</text><text id="2">hello flutter!</text></binding></visual></toast>
flutter: onShow 07afb153-163c-472b-8698-cbf777562664
flutter: onClose 07afb153-163c-472b-8698-cbf777562664 - LocalNotificationCloseReason.unknown
xml: <toast scenario="Default"><visual><binding template="ToastText02"><text id="1">example - 0</text><text id="2">hello flutter!</text></binding></visual></toast>
flutter: onShow 07afb153-163c-472b-8698-cbf777562664

**Comment by Rickaym** [comment]
I'm having this problem, how did you resolve it?

**Comment by Rickaym** [comment]
@ekokurniadi
