### ISSUE TITLE
it creates a shortcut in the windows startmenu dir

### ISSUE THREAD

**Issue by netharuM** [leanflutter/local_notifier#5]
I absolutely love this and most of your packages
but when I display the notification it creates a shortcut (.lnk) in the startup menu in the windows with the name being the title of the notification
and it's linked to the executable

is there any way to prevent this from creating or change the path that this file gets created

here are the prints in the flutter app

```
Default App User Model Id: <notification-name>
Default shell link path: C:\Users\<UserName>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\
Default shell link file path: C:\Users\<UserName>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\<notification-name>
xml: <toast scenario="Default"><visual><binding template="ToastText02"><text id="1">test</text><text id="2">test is gonna be ringing at 12:40</text></binding></visual></toast>
```

thanks 😀😀

**Comment by netharuM** [comment]
ummm i found this
in [windows/wintoastlib.cpp](../blob/main/windows/wintoastlib.cpp)

```cpp
#define DEFAULT_SHELL_LINKS_PATH	L"\\Microsoft\\Windows\\Start Menu\\Programs\\"
#define DEFAULT_LINK_FORMAT			L".lnk"
#define STATUS_SUCCESS (0x00000000)
```

but I am not that familiar with C++ 
so hope you guys can help with this I really have no idea about this 

thanks 😀😀

**Comment by lijy91** [comment]
WinToast will create a shortcut by default, I can disable it with some settings, but I'm not sure what the consequences will be
```
WinToast::instance()->setShortcutPolicy(WinToast::SHORTCUT_POLICY_IGNORE);
```

**Comment by lijy91** [comment]
Shortcuts are not created by default
