### ISSUE TITLE
现在通知超时系统关闭和手动点击关闭都是调用onClose, 能不能添加一个超时关闭的事件

### ISSUE THREAD

**Issue by j787701730** [leanflutter/local_notifier#6]
![image](https://user-images.githubusercontent.com/23625690/165205790-1f7d751b-e55c-4c5a-aaa1-0a3c94562ac4.png)

**Comment by lijy91** [comment]
看了一下 WinToast 的API，windows 平台上可以加这个功能。
https://github.com/mohabouje/WinToast/blob/a21decbe81b66890f27f1f697577d0c3a9982e0e/example/console-example/main.cpp#L25

**Comment by lijy91** [comment]
Add the parameter closeReason to the onClose event, but it is only supported on windows, other platforms closeReason is always unknown.

```dart
_exampleNotification?.onClose = (closeReason) {
  switch (closeReason) {
    case LocalNotificationCloseReason.userCanceled:
      // do something
      break;
    case LocalNotificationCloseReason.timedOut:
      // do something
      break;
    default:
  }
```
