### ISSUE TITLE
[Windows][0.1.3] 通知标题栏图标出不来

### ISSUE THREAD

**Issue by j787701730** [leanflutter/local_notifier#7]
![image](https://user-images.githubusercontent.com/23625690/165890819-9b1005a3-202a-423b-a4d2-871113160208.png)
C:\Users\<用户>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs [0.1.3]不会生成图标. [0.1.2]有生成, 但标题图标首次打开也不会展示.

**Comment by j787701730** [comment]
onShow, onClose, onClick, onClickAction. 都不写, 点击通知框好像会把程序(崩溃)关了.

**Comment by lijy91** [comment]
> onShow, onClose, onClick, onClickAction. 都不写, 点击通知框好像会把程序(崩溃)关了.

这个我似乎没有复现，晚点我尝试用 winrt 的 notification api 来替换 wintoast 。

**Comment by lijy91** [comment]
Please update to v0.1.5
