### ISSUE TITLE
Windows 10 does not show "Yes" , "No" buttons from the "Example" application

### ISSUE THREAD

**Issue by walterwatson** [leanflutter/local_notifier#9]
Hello, 

The YES/No buttons from the Example app do *NOT* show in the notification for Windows 10 Home.  The Yes/No buttons *DO* work for Linux though.  Thank you for your hard work on this project.

![image](https://user-images.githubusercontent.com/65978471/167313961-dbb7d995-3a08-44b7-9713-abf5963ff01a.png)

![image](https://user-images.githubusercontent.com/65978471/167313922-5018a105-b3f4-4314-a0f7-1b1e6fb08fc1.png)

**Comment by lijy91** [comment]
He seems to be related to SHORTCUT_POLICY https://github.com/leanflutter/local_notifier/commit/f21669607bf610ce67efbd3db673d7b5320fe7e2

**Comment by l-borkowski** [comment]
I checked example app and after removing mentioned line everything works fine, would it be fixed in near future?

**Comment by cbenhagen** [comment]
Some info why the shortcut is needed:
https://github.com/mohabouje/WinToast/issues/60
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/hh802762(v=vs.85)

**Comment by lijy91** [comment]
Please update to v0.1.5
